import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Media, PageIntro, QuoteBand, SectionHead, VideoSlot } from '@/components/site/site';
import { getImage } from '@/data/images';
import { pageHead, breadcrumb } from '@/data/seo';
const categories = ['All','Gutters','Fascia','Pillar Cladding','Balustrades','Aluminium Doors & Windows','Garage Doors'] as const;
const projectItems = Array.from({length:20}, (_,i) => ({ slot:`project-${String(i+1).padStart(2,'0')}`, category:categories[1+(i%6)], caption: ['Architectural roofline finish','Clean-lined exterior detail','Matched aluminium finishes','Glass and steel detail'][i%4] }));
export const Route = createFileRoute('/projects')({ head: () => pageHead('Projects & Finish Inspiration', 'Explore gutters, fascia, glass balustrades and aluminium finishes in our visual gallery.', '/projects', breadcrumb('Projects','/projects')), component: Projects });
function Projects() { const [filter,setFilter] = useState<string>('All'); const [active,setActive] = useState<(typeof projectItems)[number] | null>(null); const visible = projectItems.filter(item => filter === 'All' || item.category === filter); return <><PageIntro eyebrow="THE GALLERY" title="The details tell the story." text="Explore the lines, materials and finishes behind a more considered exterior." slot="balustrade-home"/><section className="section"><div className="container"><SectionHead eyebrow="VISUAL GALLERY" title="Explore by detail."/><div className="filters" role="group" aria-label="Filter projects">{categories.map(c => <Button key={c} size="sm" variant={filter===c?'brand':'outline'} onClick={() => setFilter(c)} aria-pressed={filter===c}>{c}</Button>)}</div><div className="project-grid">{visible.map(item => <Button variant="ghost" className="project-item !h-auto !block !whitespace-normal" key={item.slot} onClick={() => setActive(item)}><Media slot={item.slot}/><strong>{item.caption}</strong><small>{item.category}</small></Button>)}</div>{filter==='All' && <div className="mt-12 grid gap-4 md:grid-cols-3">{['project-video-01','project-video-02','project-video-03'].map(slot => <VideoSlot key={slot} slot={slot} className="!min-h-64"/>)}</div>}</div></section>{active && <div className="lightbox" role="dialog" aria-modal="true" aria-label={active.caption} onClick={() => setActive(null)}><Button variant="light" size="icon" aria-label="Close image"><X/></Button><img src={getImage(active.slot).src} alt={getImage(active.slot).alt} width={1600} height={1000}/><p>{active.caption} · {active.category}</p></div>}<QuoteBand/></>; }
