import { createFileRoute, Link, notFound } from '@tanstack/react-router';
import { ArrowUpRight } from 'lucide-react';
import { Eyebrow, Media, PageIntro, QuoteBand, SectionHead } from '@/components/site/site';
import { services } from '@/data/content';
import { pageHead, breadcrumb, faqSchema } from '@/data/seo';
export const Route = createFileRoute('/services/$slug')({
  loader: ({ params }) => { const service = services.find(s => s.slug === params.slug); if (!service) throw notFound(); return service; },
  head: ({ loaderData }) => loaderData ? pageHead(loaderData.title, `${loaderData.intro} Explore finishes, benefits and answers.`, `/services/${loaderData.slug}`, [{ '@context': 'https://schema.org', '@type': 'Service', name: loaderData.title, description: loaderData.intro, provider: { '@type':'HomeAndConstructionBusiness', name:'Elite Gutters and Aluminium Products' } }, faqSchema(loaderData.faqs), breadcrumb(loaderData.title, `/services/${loaderData.slug}`)]) : pageHead('Service not found', 'Explore our services.', '/'),
  component: ServicePage,
});
function ServicePage() { const s = Route.useLoaderData(); const related = services.filter(item => item.slug !== s.slug).slice(0,3); return <><PageIntro eyebrow="OUR EXPERTISE" title={s.title} text={s.short} slot={s.image}/><section className="section"><div className="container content-split"><div><Eyebrow>THE DETAILS MATTER</Eyebrow><h2>{s.short}</h2><p>{s.intro}</p><ul className="check-list">{s.benefits.map(item => <li key={item}>{item}</li>)}</ul><Eyebrow>AVAILABLE FINISHES</Eyebrow><div className="chip-list">{s.finishes.map(item => <span key={item} className="chip">{item}</span>)}</div></div><Media slot={s.image}/></div></section><section className="section section-soft"><div className="container"><SectionHead eyebrow="A CLOSER LOOK" title="The finished look."/><div className="gallery-grid">{[s.image,'hero-home','matched-charcoal-01','matched-bronze-01','matched-stainless-01'].map((slot,i) => <Media key={i} slot={slot}/>)}</div></div></section><section className="section"><div className="container faq-layout"><div><Eyebrow>GOOD TO KNOW</Eyebrow><h2>Questions,<br/>answered.</h2></div><div>{s.faqs.map(([q,a]) => <details className="faq-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></div></section><section className="section section-soft"><div className="container"><SectionHead eyebrow="KEEP EXPLORING" title="Complete the picture."/><div className="related-links">{related.map(item => <Link key={item.slug} to="/services/$slug" params={{slug:item.slug}}>{item.title}<ArrowUpRight/></Link>)}</div></div></section><QuoteBand title={`Let's talk ${s.title.toLowerCase()}.`}/></>; }
