-- Generated by scripts/gen-seed.ts from the site's built-in content. Do not edit by hand.

INSERT INTO settings (key, value) VALUES
  ('phone', '+27 84 258 6400'),
  ('whatsapp_number', '27842586400'),
  ('email', 'info@eliteguttersandaluminium.co.za'),
  ('facebook', 'https://www.facebook.com/share/19c7jqKWq7/'),
  ('address', ''),
  ('maps_embed_url', ''),
  ('company_profile_pdf', ''),
  ('founder_name', 'Mr Peter'),
  ('founder_bio', 'Mr Peter is the founder of Elite Gutters and Aluminium Products.
Talk to him about your gutters, fascia, balustrades or aluminium project: call or WhatsApp +27 84 258 6400.'),
  ('whatsapp_popup_text', 'Need seamless gutters? Send us a photo of your roofline on WhatsApp for a free quote.'),
  ('quote_text', 'Hi Elite Gutters, I''d like a quote.'),
  ('stat_years', '16'),
  ('stat_jobs', '3200'),
  ('stat_satisfaction', '99.9');

INSERT INTO projects (id, title, category, cover, position) VALUES
  (1, 'Seamless gutters on a double-storey home', 'Gutters', 'video-gutters-double-storey', 1),
  (2, 'Charcoal seamless gutters, double-storey', 'Gutters', 'charcoal-seamless-gutters-double-storey', 2),
  (3, 'Charcoal seamless gutters fitted on site', 'Gutters', 'video-gutters-single-storey', 3),
  (4, 'Fitting a seamless gutter on site', 'Gutters', 'seamless-gutter-installation-on-site', 4),
  (5, 'Charcoal seamless gutters and downpipes, finished home', 'Gutters', 'video-gutters-pillars', 5),
  (6, 'Charcoal seamless gutter and downpipe beside charcoal pillars', 'Gutters', 'charcoal-gutters-downpipes-pillars', 6),
  (7, 'Gutters and downpipes on a commercial building', 'Gutters', 'video-commercial-building', 7),
  (8, 'Commercial building gutters and downpipes', 'Gutters', 'commercial-building-gutters-downpipes', 8),
  (9, 'Gutters and downpipes on a finished home', 'Gutters', 'video-gutters-fence', 9),
  (10, 'Gutters and downpipes, finished home', 'Gutters', 'gutters-downpipes-home-with-fence', 10),
  (11, 'Charcoal gutters and fascia boards', 'Gutters', 'project-video-charcoal', 11),
  (12, 'Charcoal gutters and fascia with charcoal folding doors', 'Gutters', 'gutters-charcoal-fascia-double-storey', 12),
  (13, 'Stainless steel fascia boards and downpipes, galvanised gutters, aluminium garage doors', 'Fascia', 'pillar-stainless-fascia-two-garage-doors', 13),
  (14, 'Stainless steel fascia boards and downpipes, galvanised gutters, aluminium garage doors', 'Fascia', 'pillar-yellow-house-garage-doors', 14),
  (15, 'Bronze fascia boards and downpipes, galvanised gutters', 'Fascia', 'fascia-bronze-double-storey', 15),
  (16, 'Bronze fascia boards and downpipes, galvanised gutters', 'Fascia', 'balustrade-stainless-balconies', 16),
  (17, 'Bronze fascia boards and downpipes, galvanised gutters', 'Fascia', 'project-video-gutters', 17),
  (18, 'Stainless steel pillar cladding on a veranda', 'Pillar Cladding', 'pillar-stainless-veranda', 18),
  (19, 'Stainless steel pillar covering and balustrades', 'Pillar Cladding', 'balustrade-stainless-pillar-covering', 19),
  (20, 'Stainless steel pillar cladding and aluminium garage doors', 'Pillar Cladding', 'video-pillar-cladding-garage-doors', 20),
  (21, 'Stainless steel balustrades and pillar covering', 'Balustrades', 'balustrade-stainless-pillar-covering', 21),
  (22, 'Frameless glass staircase balustrade', 'Balustrades', 'balustrade-glass-staircase', 22),
  (23, 'Tinted glass balcony balustrade, commercial', 'Balustrades', 'balustrade-tinted-glass-commercial', 23),
  (24, 'Aluminium windows and glass balustrades, double-storey', 'Aluminium Doors & Windows', 'aluminium-windows-glass-balustrades', 24),
  (25, 'Aluminium windows on an office complex', 'Aluminium Doors & Windows', 'aluminium-commercial-complex', 25),
  (26, 'Aluminium windows and doors, new build', 'Aluminium Doors & Windows', 'aluminium-new-build', 26),
  (27, 'Three charcoal aluminium glass garage doors', 'Garage Doors', 'garage-three-charcoal-glass', 27),
  (28, 'Arched glass garage doors with matching gate', 'Garage Doors', 'garage-arched-glass-gate', 28),
  (29, 'Automated garage doors by remote control', 'Garage Doors', 'project-video-garage', 29),
  (30, 'Aluminium glass garage doors and stainless steel pillar cladding', 'Garage Doors', 'video-pillar-cladding-garage-doors', 30),
  (31, 'Bronze retractable burglar proofing', 'Burglar Proofing', 'burglar-proofing-folding-doors', 31),
  (32, 'Retractable burglar proofing behind charcoal windows', 'Burglar Proofing', 'burglar-proofing-windows', 32),
  (33, 'Retractable burglar proofing behind bronze windows', 'Burglar Proofing', 'burglar-proofing-bronze-windows', 33),
  (34, 'Torch-on waterproofing on a flat roof', 'Waterproofing', 'waterproofing-flat-roof-finished', 34),
  (35, 'Flat roof and parapets sealed with torch-on', 'Waterproofing', 'video-waterproofing-flat-roof', 35),
  (36, 'Torch-on waterproofing over parapet edges', 'Waterproofing', 'waterproofing-roof-edges', 36),
  (37, 'Torch-on membrane rolls delivered to site', 'Waterproofing', 'video-waterproofing-membrane', 37),
  (38, 'Tiled roof painted grey', 'Roof & Wall Painting', 'roof-painting-tile-roof', 38),
  (39, 'Painted tiled and metal sheet roofs', 'Roof & Wall Painting', 'video-roof-painting', 39),
  (40, 'Painted tiled roof along the ridge', 'Roof & Wall Painting', 'roof-painting-ridge', 40),
  (41, 'Painted metal sheet roof', 'Roof & Wall Painting', 'roof-painting-metal-roof-house', 41);

INSERT INTO project_images (project_id, slot, position) VALUES
  (1, 'video-gutters-double-storey', 1),
  (2, 'charcoal-seamless-gutters-double-storey', 1),
  (3, 'video-gutters-single-storey', 1),
  (4, 'seamless-gutter-installation-on-site', 1),
  (5, 'video-gutters-pillars', 1),
  (6, 'charcoal-gutters-downpipes-pillars', 1),
  (7, 'video-commercial-building', 1),
  (8, 'commercial-building-gutters-downpipes', 1),
  (9, 'video-gutters-fence', 1),
  (10, 'gutters-downpipes-home-with-fence', 1),
  (11, 'project-video-charcoal', 1),
  (12, 'gutters-charcoal-fascia-double-storey', 1),
  (13, 'pillar-stainless-fascia-two-garage-doors', 1),
  (14, 'pillar-yellow-house-garage-doors', 1),
  (15, 'fascia-bronze-double-storey', 1),
  (16, 'balustrade-stainless-balconies', 1),
  (17, 'project-video-gutters', 1),
  (18, 'pillar-stainless-veranda', 1),
  (19, 'balustrade-stainless-pillar-covering', 1),
  (20, 'video-pillar-cladding-garage-doors', 1),
  (21, 'balustrade-stainless-pillar-covering', 1),
  (22, 'balustrade-glass-staircase', 1),
  (23, 'balustrade-tinted-glass-commercial', 1),
  (24, 'aluminium-windows-glass-balustrades', 1),
  (25, 'aluminium-commercial-complex', 1),
  (26, 'aluminium-new-build', 1),
  (27, 'garage-three-charcoal-glass', 1),
  (28, 'garage-arched-glass-gate', 1),
  (29, 'project-video-garage', 1),
  (30, 'video-pillar-cladding-garage-doors', 1),
  (31, 'burglar-proofing-folding-doors', 1),
  (32, 'burglar-proofing-windows', 1),
  (33, 'burglar-proofing-bronze-windows', 1),
  (34, 'waterproofing-flat-roof-finished', 1),
  (35, 'video-waterproofing-flat-roof', 1),
  (36, 'waterproofing-roof-edges', 1),
  (37, 'video-waterproofing-membrane', 1),
  (38, 'roof-painting-tile-roof', 1),
  (39, 'video-roof-painting', 1),
  (40, 'roof-painting-ridge', 1),
  (41, 'roof-painting-metal-roof-house', 1);

INSERT INTO services (id, slug, title, short, intro, benefits, finishes, faqs, cover, banner, position) VALUES
  (1, 'seamless-gutters', 'Seamless Gutters', 'Clean lines. Confident protection.', 'Stainless steel and colour-coated seamless gutters and downpipes, formed to fit your roofline. Fewer joints mean a cleaner finish and far fewer places for water to escape. Choose rust-free stainless steel or a colour-coated finish such as charcoal or bronze to match your fascia, windows and doors.', 'Continuous lengths for a neat, uninterrupted roofline
Rainwater runs freely to the downpipes without damaging your walls
Wider profiles move rainwater away faster in heavy rain
Rust-free stainless steel and colour-coated steel options
Downpipes finished to match your gutters
Low maintenance, with fewer joints to check
Built to last 20 years', 'Stainless steel
Charcoal
Bronze
Black
Colour-coated steel', 'What makes a gutter seamless?
Seamless gutters are formed in continuous lengths to fit the roofline, so there are no joints along each run. That means a cleaner look and far fewer places for leaks to start.

How long do your seamless gutters last?
Our seamless gutters are built to last 20 years. With no joints to work loose and a finish that resists rust, they keep carrying water away from your walls year after year.

Are stainless steel gutters rust-free?
Yes. Stainless steel does not rust like ordinary steel, which makes it a durable, long-lasting choice for gutters and downpipes.

Can the downpipes match the gutters?
Yes. Downpipes are supplied in the same finish as your gutters, and we can match them to your fascia boards, windows and doors too.

Do you install gutters on commercial buildings?
Yes. Our wider gutter profiles suit large roofs on warehouses, factories, schools and commercial buildings.', 'colour-range-chart', 'colour-range-chart', 1),
  (2, 'box-gutters', 'Industrial Box Gutters', 'Built for big roofs and heavy rain.', 'Heavy-duty box gutters for factories, warehouses and commercial buildings. Wide, deep profiles carry large volumes of rainwater off big roof areas and into downpipes sized to match, so water leaves the roof instead of backing up.', 'Wide, deep profiles for large roof areas
Made to handle heavy downpours
Downpipes and outlets sized to match
Suited to factories, warehouses and commercial buildings', '', 'What is a box gutter?
A box gutter is a wide, square-sided gutter, often set between two roof slopes or behind a parapet wall. Its size lets it carry the large volumes of water that run off industrial and commercial roofs.

Which buildings need box gutters?
Factories, warehouses, workshops, schools and other commercial buildings with large roof areas, where ordinary domestic gutters would overflow.

Can you replace an old, leaking box gutter?
Yes. Send us photos of the roof and the existing gutter via WhatsApp and we will advise on a replacement.', '', '', 2),
  (3, 'fascia-boards', 'Fascia Boards & Bargeboards', 'The finish that frames it all.', 'Stainless steel, bronze and charcoal fascia boards and bargeboards give your roofline a crisp architectural edge while protecting the roof timber behind them. They also give your gutters a solid base, and are rust-free, low maintenance and made to match your gutters for one clean, continuous look.', 'Installation and replacement of fascias and bargeboards
Rust-free stainless steel and colour-coated options
Protects roof timbers from the weather
A solid base for your gutters
Made to match your gutters and downpipes
No painting or regular upkeep needed', 'Stainless steel
Bronze
Charcoal
Colour-coated steel', 'Can fascia boards match my gutters?
Yes. Matching fascia boards and gutters is our signature. We supply both in the same finish for a seamless roofline.

What finishes are available?
Stainless steel, bronze and charcoal are popular choices, alongside our full range of colour-coated steel.

Do metal fascia boards rust?
Stainless steel fascia boards are rust-free, and colour-coated steel is finished to stand up to the weather.

What is the difference between a fascia and a bargeboard?
A fascia board runs along the bottom edge of the roof, where the gutters are fixed. A bargeboard finishes the sloping edge of a gable end. We fit both in matching finishes.

Can you replace old timber fascia boards?
Yes. Send us photos of your existing roofline and we will advise on the best replacement.', 'pillar-stainless-fascia-two-garage-doors', '', 3),
  (4, 'water-harvesting', 'Water Harvesting Systems', 'Catch the rain. Use it later.', 'We set up the downpipes and connections that carry rainwater from your gutters into rainwater harvesting tanks. It is an eco-friendly way to save water and reduce your utility bills.', 'Downpipes routed to your rainwater tanks
Connections for new or existing tanks
Less reliance on municipal water
Lower water bills
Pairs well with new seamless gutters', '', 'Can you connect my existing tank?
Yes. Send us photos of the tank and your roofline via WhatsApp and we will advise on the best way to route the downpipes.

Do I need new gutters for rainwater harvesting?
Not always. If your gutters are in good condition we can connect to them. If they leak or overflow, new seamless gutters will catch more of the rain.

What can harvested rainwater be used for?
Watering the garden, washing cars and paving, and topping up the pool are common uses.', '', '', 4),
  (5, 'gutter-cleaning', 'Gutter Cleaning', 'Clear gutters. Free-flowing water.', 'Professional gutter cleaning to remove leaves, debris and blockages. Regular cleaning prevents water damage and extends the life of your gutters.', 'Leaves, debris and blockages removed
Downpipes cleared so water can drain
Helps prevent overflow and water damage
Extends the life of your gutters', '', 'How often should gutters be cleaned?
Most homes benefit from a clean at least once a year, and more often if trees overhang the roof. Just before the rainy season is a good time.

What happens if gutters are not cleaned?
Blocked gutters overflow, which can damage fascia boards, walls and foundations. The extra weight of wet debris can also make gutters sag.

Do seamless gutters need less cleaning?
Yes. With no joints along the run, debris has fewer places to catch, but they still need an occasional clean.', '', '', 5),
  (6, 'pillar-cladding', 'Pillar Cladding', 'Give structure a sharper edge.', 'Stainless steel pillar cladding covers existing pillars in a sleek, modern finish. It protects the pillar from knocks and weather, and ties in with your gutters, fascia and balustrades.', 'Modern, architectural appearance
Protects pillars from weather and everyday knocks
Rust-free stainless steel construction
Complements matched gutters, fascia and balustrades', 'Brushed stainless steel
Polished stainless steel', 'What is pillar cladding?
Pillar cladding is a fitted stainless steel covering that gives an existing pillar a clean, modern finish and protects it.

Can it be fitted to existing pillars?
Yes. We measure each pillar and fit cladding to suit it.

Where is pillar cladding used?
It works well on entrances, patios, carports, balconies and commercial frontages.', 'pillar-stainless-veranda', 'pillar-stainless-fascia-two-garage-doors', 6),
  (7, 'balustrades', 'Balustrades', 'Open views. Beautiful boundaries.', 'Glass balustrades and stainless steel balustrades for balconies, staircases and handrails. They keep spaces safe without closing off the view, and finish your home with clean, modern lines.', 'Glass balustrades that keep views open
Stainless steel balustrades and handrails
Staircase, balcony and patio applications
Rust-free, low-maintenance materials', 'Clear glass
Stainless steel
Glass with stainless steel', 'Where can balustrades be installed?
Balconies, staircases, patios, mezzanines and any raised area that needs a safe, good-looking edge.

Do you offer glass balustrades?
Yes. We install glass balustrades on their own or combined with stainless steel posts and handrails.

Do you do staircase balustrades and handrails?
Yes. Staircase balustrades and handrails are part of our range, inside and outside.

Can I get a quote for an existing staircase?
Yes. Send photos and rough measurements via WhatsApp and we will take it from there.', 'balustrade-glass-staircase', 'balustrade-tinted-glass-commercial', 7),
  (8, 'aluminium-doors-windows', 'Aluminium Doors & Windows', 'Frame every view beautifully.', 'Aluminium windows, doors, folding doors and shopfronts in bronze, charcoal and more. Aluminium folding doors open up patios, gazebos and living areas, and every frame can be matched to your gutters and fascia boards.', 'Slim, strong aluminium frames
Aluminium folding doors for patios and gazebos
Shopfronts for commercial premises
Frames matched to your fascia and gutters', 'Bronze
Charcoal
Black
Silver', 'Do you install aluminium folding doors?
Yes. Aluminium folding doors are ideal for patios, gazebos and entertainment areas, opening the space up completely.

Can window frames match my fascia boards?
Yes. Bronze fascia with bronze aluminium folding doors is one of our favourite combinations.

Do you do shopfronts?
Yes. We supply and install aluminium shopfronts for commercial premises.', 'aluminium-windows-glass-balustrades', '', 8),
  (9, 'garage-doors', 'Garage Doors', 'A strong first impression.', 'Single and double aluminium garage doors, fully automated with remote control. Clean, modern and matched to your roofline, so your home looks complete from the street.', 'Single and double garage doors
Fully automated with remote control
Durable, low-maintenance aluminium
Finished to match gutters and fascia', 'Charcoal
Bronze
Black
Wood-look', 'Are your garage doors automated?
Yes. Our automated garage doors open and close by remote control.

Do you offer single and double doors?
Yes. Both single and double aluminium garage doors are available.

Can the garage door match my gutters?
Yes. Charcoal gutters, charcoal fascia and a charcoal garage door is a popular matched look.', 'garage-three-charcoal-glass', '', 9),
  (10, 'burglar-proofing', 'Burglar Proofing', 'Security without compromise.', 'Retractable, glass and aluminium burglar proofing that keeps your home secure without spoiling the view. Retractable burglar proofing folds away to the side when you want the opening clear, and closes across windows and doors when you need it. Finished to suit your frames.', 'Retractable burglar proofing that folds away to the side
Security with a modern look
Glass and aluminium options
Keeps natural light and views
Finished to match your window frames', 'Clear glass
Aluminium
Charcoal
Bronze', 'What materials do you use?
We offer retractable, glass and aluminium burglar proofing, designed to be secure and good-looking.

Do you do retractable burglar proofing?
Yes. Retractable burglar proofing closes across windows, doors and wide openings, and folds away to the side when you want it open.

Will it suit a modern home?
Yes. It is designed as a clean, modern alternative to traditional burglar bars.

Can I send a photo for a quote?
Yes. Send photos of your windows or doors via WhatsApp and we will get back to you.', 'burglar-proofing-folding-doors', '', 10),
  (11, 'gutter-repairs', 'Repairs & Maintenance', 'Fix the leak before it spreads.', 'Repair services for existing gutters. We fix leaks, re-align sagging gutters and replace damaged sections so your gutters work properly again and send water to the downpipes, not down your walls.', 'Leaking joints and sections sealed
Sagging gutters re-aligned and re-supported
Damaged sections and downpipes replaced
Water carried away from walls and foundations', '', 'Why are my gutters sagging?
Sagging usually comes from loose or missing brackets, or from the weight of water and debris sitting in a blocked gutter. Re-aligning and re-supporting the run lets water flow to the downpipes again.

Can you repair gutters you did not install?
Yes. Send us photos of the problem via WhatsApp and we will advise whether a repair or a replacement makes more sense.

When is replacement better than repair?
If an old sectional gutter leaks at many joints, replacing it with a seamless gutter is often the better long-term option.', '', '', 11),
  (12, 'waterproofing', 'Torch-on Waterproofing', 'Keep the rain on the outside.', 'Torch-on waterproofing and rubberiser for flat roofs, parapet walls, balconies and box gutters. A leaking roof rarely stays a small problem: water soaks into ceilings, stains walls, rots roof timbers and brings damp and mould into the home. We seal the surface so rainwater runs off instead of finding its way inside.', 'Torch-on membrane for flat concrete roofs and parapets
Rubberiser coating for edges, joints and awkward details
Balconies, box gutters and roof leaks
Surfaces cleaned and prepared before sealing
Stops damp, stains and mould before they spread', '', 'What is torch-on waterproofing?
Torch-on is a bitumen membrane supplied in rolls. It is heated with a gas torch as it is laid, so it melts onto the roof surface and bonds in place. The overlapping rolls form one continuous waterproof layer.

What is rubberiser?
Rubberiser is a liquid rubber waterproofing coating applied by brush or roller. It stays flexible, so it suits joints, edges, small roofs and areas where a membrane is hard to fit.

Which surfaces can you waterproof?
Flat concrete roofs, parapet walls, balconies, box gutters and other areas where water sits or runs.

My roof is leaking. Can you help?
Yes. Send us photos of the roof and the damp patches inside via WhatsApp and we will advise on the best way to seal it.', 'waterproofing-flat-roof-parapet', 'waterproofing-banner', 12),
  (13, 'roof-wall-painting', 'Roof & Wall Painting', 'A fresh finish from the top down.', 'Roof painting and wall painting that make a tired building look new again. We paint tiled roofs, metal sheet roofs and exterior walls, preparing each surface first so the paint holds. Choose a colour to match your gutters, fascia boards and window frames for one finished look.', 'Tiled roofs and metal sheet roofs
Exterior wall painting
Surfaces cleaned and prepared before painting
Colours to match your gutters, fascia and frames
Protects roofs and walls from sun and weather', '', 'Which roofs can you paint?
Concrete tiled roofs and metal sheet roofs, such as corrugated and IBR.

Do you paint walls as well?
Yes. We paint exterior walls, boundary walls and parapets.

Can the roof colour match my gutters?
Yes. Choose a roof colour that works with your gutters, fascia boards and window frames for a finished, matching look.

How do I get a quote?
Send us photos of the roof or walls via WhatsApp and we will get back to you with a quote.', 'roof-painting-tile-roof', 'roof-painting-banner', 13);

INSERT INTO service_images (service_id, slot, label, position) VALUES
  (1, 'colour-range-chart', '', 1),
  (1, 'charcoal-seamless-gutters-double-storey', '', 2),
  (1, 'seamless-gutter-installation-on-site', '', 3),
  (1, 'charcoal-gutters-downpipes-pillars', '', 4),
  (1, 'gutters-downpipes-home-with-fence', '', 5),
  (1, 'commercial-building-gutters-downpipes', '', 6),
  (1, 'gutters-charcoal-fascia-double-storey', '', 7),
  (3, 'pillar-stainless-fascia-two-garage-doors', 'Stainless steel fascia boards', 1),
  (3, 'pillar-yellow-house-garage-doors', 'Stainless steel fascia boards', 2),
  (3, 'fascia-bronze-double-storey', 'Bronze fascia boards', 3),
  (3, 'balustrade-stainless-balconies', 'Bronze fascia boards', 4),
  (3, 'gutters-charcoal-fascia-double-storey', 'Charcoal fascia boards', 5),
  (6, 'pillar-stainless-veranda', 'Stainless steel pillar cladding', 1),
  (6, 'balustrade-stainless-pillar-covering', 'Stainless steel pillar covering', 2),
  (6, 'pillar-stainless-fascia-two-garage-doors', 'Stainless steel pillar cladding', 3),
  (6, 'pillar-yellow-house-garage-doors', 'Stainless steel pillar cladding', 4),
  (7, 'balustrade-stainless-pillar-covering', 'Stainless steel balustrades', 1),
  (7, 'balustrade-glass-staircase', 'Frameless glass balustrade', 2),
  (7, 'balustrade-tinted-glass-commercial', 'Tinted glass balustrades', 3),
  (8, 'aluminium-windows-glass-balustrades', 'Aluminium windows', 1),
  (8, 'aluminium-commercial-complex', 'Aluminium windows, office complex', 2),
  (8, 'aluminium-new-build', 'Aluminium windows and doors', 3),
  (9, 'garage-three-charcoal-glass', 'Charcoal aluminium garage doors', 1),
  (9, 'garage-arched-glass-gate', 'Arched glass garage doors', 2),
  (9, 'pillar-stainless-fascia-two-garage-doors', 'Aluminium garage doors', 3),
  (9, 'pillar-yellow-house-garage-doors', 'Aluminium garage doors', 4),
  (10, 'burglar-proofing-folding-doors', 'Retractable burglar proofing', 1),
  (10, 'burglar-proofing-windows', 'Retractable burglar proofing', 2),
  (10, 'burglar-proofing-bronze-windows', 'Retractable burglar proofing', 3),
  (12, 'waterproofing-flat-roof-parapet', 'Torch-on waterproofing, flat roof', 1),
  (12, 'waterproofing-membrane-rolls', 'Torch-on membrane rolls', 2),
  (13, 'roof-painting-tile-roof', 'Painted gable wall and tiled roof', 1);

INSERT INTO page_photos (key, slot, position) VALUES
  ('home-spotlight', 'gutter-downpipe-example', 1),
  ('home-matched-1', 'matched-bronze-01', 2),
  ('home-matched-2', 'matched-charcoal-01', 3),
  ('home-matched-3', 'matched-stainless-01', 4),
  ('home-mosaic-1', 'commercial-building-gutters-downpipes', 5),
  ('home-mosaic-2', 'seamless-gutter-installation-on-site', 6),
  ('home-mosaic-3', 'colour-range-chart', 7),
  ('home-mosaic-4', 'garage-three-charcoal-glass', 8),
  ('home-mosaic-5', 'gutters-charcoal-fascia-double-storey', 9),
  ('home-mosaic-6', 'charcoal-seamless-gutters-double-storey', 10),
  ('home-band-1', 'colour-range-chart', 11),
  ('home-band-2', 'fascia-bronze-double-storey', 12),
  ('quote-band', 'garage-three-charcoal-glass', 13),
  ('about-banner', 'balustrade-stainless-balconies', 14),
  ('about-photo', 'about-01', 15),
  ('founder-photo', 'founder', 16),
  ('why-banner', 'pillar-stainless-fascia-two-garage-doors', 17),
  ('why-photo-1', 'fascia-bronze-double-storey', 18),
  ('why-photo-2', 'pillar-stainless-veranda', 19),
  ('benefits-banner', 'fascia-bronze-double-storey', 20),
  ('benefits-photo-1', 'gutter-closeup-illustration', 21),
  ('benefits-photo-2', 'gutters-charcoal-fascia-double-storey', 22),
  ('colour-banner', 'fascia-bronze-double-storey', 23),
  ('colour-chart', 'colour-range-chart', 24),
  ('commercial-banner', 'commercial-hero', 25),
  ('commercial-photo', 'commercial-key-01', 26),
  ('projects-banner', 'aluminium-commercial-complex', 27),
  ('contact-banner', 'aluminium-windows-glass-balustrades', 28);
