// Writes migrations/0002_seed.sql from the content that ships with the site
// (content.ts, page-photos.ts), so after the switch to D1 the site looks identical.
// Run with: bun scripts/gen-seed.ts
import { writeFileSync } from "node:fs";
import { projects, services } from "../src/data/content";
import { formatFaqs, settingDefaults } from "../src/data/live";
import { pagePhotoSpots } from "../src/data/page-photos";

const q = (value: string | number) =>
  typeof value === "number" ? String(value) : `'${value.replace(/'/g, "''")}'`;
const row = (...values: (string | number)[]) => `(${values.map(q).join(", ")})`;

const out: string[] = [
  "-- Generated by scripts/gen-seed.ts from the site's built-in content. Do not edit by hand.",
  "",
];

out.push("INSERT INTO settings (key, value) VALUES");
out.push(
  Object.entries(settingDefaults)
    .map(([key, value]) => `  ${row(key, value)}`)
    .join(",\n") + ";",
  "",
);

out.push("INSERT INTO projects (id, title, category, cover, position) VALUES");
out.push(
  projects.map((p, i) => `  ${row(i + 1, p.caption, p.category, p.slot, i + 1)}`).join(",\n") + ";",
  "",
);
out.push("INSERT INTO project_images (project_id, slot, position) VALUES");
out.push(projects.map((p, i) => `  ${row(i + 1, p.slot, 1)}`).join(",\n") + ";", "");

out.push(
  "INSERT INTO services (id, slug, title, short, intro, benefits, finishes, faqs, cover, banner, position) VALUES",
);
out.push(
  services
    .map(
      (s, i) =>
        `  ${row(
          i + 1,
          s.slug,
          s.title,
          s.short,
          s.intro,
          s.benefits.join("\n"),
          s.finishes.join("\n"),
          formatFaqs(s.faqs),
          s.image ?? "",
          "banner" in s ? s.banner : "",
          i + 1,
        )}`,
    )
    .join(",\n") + ";",
  "",
);
const gallery = services.flatMap((s, i) =>
  s.gallery.map((slot, j) => {
    const labels: Record<string, string> = "photoLabels" in s ? s.photoLabels : {};
    return `  ${row(i + 1, slot, labels[slot] ?? "", j + 1)}`;
  }),
);
out.push("INSERT INTO service_images (service_id, slot, label, position) VALUES");
out.push(gallery.join(",\n") + ";", "");

out.push("INSERT INTO page_photos (key, slot, position) VALUES");
out.push(pagePhotoSpots.map((p, i) => `  ${row(p.key, p.slot, i + 1)}`).join(",\n") + ";", "");

writeFileSync("migrations/0002_seed.sql", out.join("\n"));
console.log(
  `Seeded ${projects.length} projects, ${services.length} services, ${gallery.length} service photos, ${pagePhotoSpots.length} page photos.`,
);
