/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenefitsOfSeamlessGuttersRouteImport } from './routes/benefits-of-seamless-gutters'
import { Route as ColourRangeRouteImport } from './routes/colour-range'
import { Route as CommercialIndustrialRouteImport } from './routes/commercial-industrial'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as WhySeamlessGuttersRouteImport } from './routes/why-seamless-gutters'
import { Route as AdminDashRouteImport } from './routes/admin/_dash'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as MediaSplatRouteImport } from './routes/media/$'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminDashIndexRouteImport } from './routes/admin/_dash/index'
import { Route as AdminDashPhotosRouteImport } from './routes/admin/_dash/photos'
import { Route as AdminDashSettingsRouteImport } from './routes/admin/_dash/settings'
import { Route as AdminDashProjectsIndexRouteImport } from './routes/admin/_dash/projects.index'
import { Route as AdminDashProjectsIdRouteImport } from './routes/admin/_dash/projects.$id'
import { Route as AdminDashServicesIndexRouteImport } from './routes/admin/_dash/services.index'
import { Route as AdminDashServicesIdRouteImport } from './routes/admin/_dash/services.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsOfSeamlessGuttersRoute =
  BenefitsOfSeamlessGuttersRouteImport.update({
    id: '/benefits-of-seamless-gutters',
    path: '/benefits-of-seamless-gutters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ColourRangeRoute = ColourRangeRouteImport.update({
  id: '/colour-range',
  path: '/colour-range',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialIndustrialRoute = CommercialIndustrialRouteImport.update({
  id: '/commercial-industrial',
  path: '/commercial-industrial',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const WhySeamlessGuttersRoute = WhySeamlessGuttersRouteImport.update({
  id: '/why-seamless-gutters',
  path: '/why-seamless-gutters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashRoute = AdminDashRouteImport.update({
  id: '/admin/_dash',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashIndexRoute = AdminDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashPhotosRoute = AdminDashPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashSettingsRoute = AdminDashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashProjectsIndexRoute = AdminDashProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashProjectsIdRoute = AdminDashProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashServicesIndexRoute = AdminDashServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminDashRoute,
} as any)
const AdminDashServicesIdRoute = AdminDashServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AdminDashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin': typeof AdminDashRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/photos': typeof AdminDashPhotosRoute
  '/admin/settings': typeof AdminDashSettingsRoute
  '/admin/': typeof AdminDashIndexRoute
  '/admin/projects/$id': typeof AdminDashProjectsIdRoute
  '/admin/services/$id': typeof AdminDashServicesIdRoute
  '/admin/projects/': typeof AdminDashProjectsIndexRoute
  '/admin/services/': typeof AdminDashServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/photos': typeof AdminDashPhotosRoute
  '/admin/settings': typeof AdminDashSettingsRoute
  '/admin': typeof AdminDashIndexRoute
  '/admin/projects/$id': typeof AdminDashProjectsIdRoute
  '/admin/services/$id': typeof AdminDashServicesIdRoute
  '/admin/projects': typeof AdminDashProjectsIndexRoute
  '/admin/services': typeof AdminDashServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits-of-seamless-gutters': typeof BenefitsOfSeamlessGuttersRoute
  '/colour-range': typeof ColourRangeRoute
  '/commercial-industrial': typeof CommercialIndustrialRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/why-seamless-gutters': typeof WhySeamlessGuttersRoute
  '/admin/_dash': typeof AdminDashRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/_dash/photos': typeof AdminDashPhotosRoute
  '/admin/_dash/settings': typeof AdminDashSettingsRoute
  '/admin/_dash/': typeof AdminDashIndexRoute
  '/admin/_dash/projects/$id': typeof AdminDashProjectsIdRoute
  '/admin/_dash/services/$id': typeof AdminDashServicesIdRoute
  '/admin/_dash/projects/': typeof AdminDashProjectsIndexRoute
  '/admin/_dash/services/': typeof AdminDashServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin'
    | '/admin/login'
    | '/api/$'
    | '/media/$'
    | '/services/$slug'
    | '/admin/photos'
    | '/admin/settings'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/services/$id'
    | '/admin/projects/'
    | '/admin/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin/login'
    | '/api/$'
    | '/media/$'
    | '/services/$slug'
    | '/admin/photos'
    | '/admin/settings'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/services/$id'
    | '/admin/projects'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/benefits-of-seamless-gutters'
    | '/colour-range'
    | '/commercial-industrial'
    | '/contact'
    | '/projects'
    | '/why-seamless-gutters'
    | '/admin/_dash'
    | '/admin/login'
    | '/api/$'
    | '/media/$'
    | '/services/$slug'
    | '/admin/_dash/photos'
    | '/admin/_dash/settings'
    | '/admin/_dash/'
    | '/admin/_dash/projects/$id'
    | '/admin/_dash/services/$id'
    | '/admin/_dash/projects/'
    | '/admin/_dash/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BenefitsOfSeamlessGuttersRoute: typeof BenefitsOfSeamlessGuttersRoute
  ColourRangeRoute: typeof ColourRangeRoute
  CommercialIndustrialRoute: typeof CommercialIndustrialRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  WhySeamlessGuttersRoute: typeof WhySeamlessGuttersRoute
  AdminDashRoute: typeof AdminDashRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  MediaSplatRoute: typeof MediaSplatRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits-of-seamless-gutters': {
      id: '/benefits-of-seamless-gutters'
      path: '/benefits-of-seamless-gutters'
      fullPath: '/benefits-of-seamless-gutters'
      preLoaderRoute: typeof BenefitsOfSeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colour-range': {
      id: '/colour-range'
      path: '/colour-range'
      fullPath: '/colour-range'
      preLoaderRoute: typeof ColourRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-industrial': {
      id: '/commercial-industrial'
      path: '/commercial-industrial'
      fullPath: '/commercial-industrial'
      preLoaderRoute: typeof CommercialIndustrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-seamless-gutters': {
      id: '/why-seamless-gutters'
      path: '/why-seamless-gutters'
      fullPath: '/why-seamless-gutters'
      preLoaderRoute: typeof WhySeamlessGuttersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_dash': {
      id: '/admin/_dash'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_dash/': {
      id: '/admin/_dash/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminDashIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/photos': {
      id: '/admin/_dash/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AdminDashPhotosRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/settings': {
      id: '/admin/_dash/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminDashSettingsRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/projects/': {
      id: '/admin/_dash/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminDashProjectsIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/projects/$id': {
      id: '/admin/_dash/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminDashProjectsIdRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/services/': {
      id: '/admin/_dash/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminDashServicesIndexRouteImport
      parentRoute: typeof AdminDashRoute
    }
    '/admin/_dash/services/$id': {
      id: '/admin/_dash/services/$id'
      path: '/services/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminDashServicesIdRouteImport
      parentRoute: typeof AdminDashRoute
    }
  }
}

interface AdminDashRouteChildren {
  AdminDashPhotosRoute: typeof AdminDashPhotosRoute
  AdminDashSettingsRoute: typeof AdminDashSettingsRoute
  AdminDashIndexRoute: typeof AdminDashIndexRoute
  AdminDashProjectsIdRoute: typeof AdminDashProjectsIdRoute
  AdminDashServicesIdRoute: typeof AdminDashServicesIdRoute
  AdminDashProjectsIndexRoute: typeof AdminDashProjectsIndexRoute
  AdminDashServicesIndexRoute: typeof AdminDashServicesIndexRoute
}

const AdminDashRouteChildren: AdminDashRouteChildren = {
  AdminDashPhotosRoute: AdminDashPhotosRoute,
  AdminDashSettingsRoute: AdminDashSettingsRoute,
  AdminDashIndexRoute: AdminDashIndexRoute,
  AdminDashProjectsIdRoute: AdminDashProjectsIdRoute,
  AdminDashServicesIdRoute: AdminDashServicesIdRoute,
  AdminDashProjectsIndexRoute: AdminDashProjectsIndexRoute,
  AdminDashServicesIndexRoute: AdminDashServicesIndexRoute,
}

const AdminDashRouteWithChildren = AdminDashRoute._addFileChildren(
  AdminDashRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BenefitsOfSeamlessGuttersRoute: BenefitsOfSeamlessGuttersRoute,
  ColourRangeRoute: ColourRangeRoute,
  CommercialIndustrialRoute: CommercialIndustrialRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  WhySeamlessGuttersRoute: WhySeamlessGuttersRoute,
  AdminDashRoute: AdminDashRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  MediaSplatRoute: MediaSplatRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
